package:
  name: hello_pybind
  version: 0.1

build:
  number: 0.1

source:
  path: ../

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - pybind11 
    - cmake

  host:
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - pybind11 
    - cmake


  run:
    - libstdcxx-ng
    - python

test:
  requires:
    - libstdcxx-ng
    - pytest

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
