package:
  name: hello_pybind
  version: 0.1

build:
  number: 0.1

source:
  path: ../

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - pybind11 
    - cmake

  host:
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - pybind11 
    - cmake


  run:
    - libcxx
    - python

test:
  requires:
    - libcxx
    - pytest
    
  files:
    - ../tests/test_pha.py
    - ../tests/__init__.py
    
  imports:
    - hello_pybind

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
